# Appearance

# Enable activity alerts
setw -g monitor-activity on
set -g visual-activity on
set -g status-interval 10
bind r source-file ~/.tmux.conf \; display "#[fg=colour15]tmux.conf reloaded!"


# get the dotfiles directory
# !!! DOTFILES is a variable that should be set in your shell profile
DOTFILES_TMUX=$DOTFILES/tmux

# Import the theme.conf file
source-file $DOTFILES_TMUX/theme.conf

# Import the pane.conf file
source-file $DOTFILES_TMUX/pane.conf

# Import the window.conf file
source-file $DOTFILES_TMUX/window.conf

# Import the popup.conf file
source-file $DOTFILES_TMUX/popup.conf


# Set prefix to C-x
set -g prefix C-x
unbind C-b
bind C-x send-prefix


# Copy and Paste
bind Escape copy-mode
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-selection
unbind p
bind p pasteb
setw -g mode-keys vi      # Vi风格选择文本
set -g mouse on


