#######################################################
# TMUX configuration file
# Author: Rouge Lin
# This is a part of my dotfiles

# Enable activity alerts
setw -g monitor-activity on
set -g visual-activity on
set -g status-interval 10
bind r source-file ~/.tmux.conf \; display "#[fg=colour15]tmux.conf reloaded!"


# get the dotfiles directory
# !!! DOTFILES is a variable that should be set in your shell profile
# Import all .conf files in the $DOTFILES_TMUX directory

DOTFILES_TMUX=$DOTFILES/tmux
source-file $DOTFILES_TMUX/*.conf


# Set prefix to C-x
set -g prefix C-x
unbind C-b
bind C-x send-prefix

