# This is the configuration file for the clip.

set -g mouse on

set -s set-clipboard on




########### Key bindings ###########

bind Escape copy-mode
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-selection
unbind p
bind p pasteb
setw -g mode-keys vi      # Vi风格选择文本
set -g mouse on
