# This is about the pane configuration file of tmux
# The pane is a part of the tmux window
# The pane is loaded by the tmux configuration file

# Set the base index of the pane
set-option -g pane-base-index 1


# Set the display time of the pane
set-option -g display-panes-time 1000 # milliseconds


# Switch the pane in vim mode
bind h select-pane -L       # 切换到左边的 Pane
bind j select-pane -D       # 切换到下边的 Pane
bind k select-pane -U       # 切换到上边的 Pane
bind l select-pane -R       # 切换到右边的 Pane


# Resize the pane in vim mode
bind -r H resize-pane -L 5  # 将当前 Pane 的宽度增加 5
bind -r J resize-pane -D 5  # 将当前 Pane 的高度增加 5
bind -r K resize-pane -U 5  # 将当前 Pane 的高度减少 5
bind -r L resize-pane -R 5  # 将当前 Pane 的宽度减少 5


# Create the new pane in current window
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"
