# This is the configuration file for the popup.

# 添加边框和颜色
set -g popup-border-style fg=colour15  # 青色边框
set -g popup-border-lines rounded      # 圆角边框（需终端支持）

# 更健壮的版本（处理特殊符号）
bind-key -r P command-prompt -p "Do what in popup?" \
"display-popup -w 80% -h 80% -E -d '#{pane_current_path}' 'bash -ci \"%1; echo; echo \\\"Prass CTRL-D to close the popup!\\\"; exec $SHELL\"'"

