# This is about the theme configuration file of tmux
# The theme is a set of variables that are used to define the look of the tmux status bar
# The theme is loaded by the tmux configuration file

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"


#################### Status bar theme ####################
set -g status-style default # Set the style of the status bar

# Set the left part of the status bar
set -g status-left-length 60 # Set the length of the left part of the status bar
set -g status-left "#[fg=colour0,bg=colour15] S#S #[fg=colour15,bg=colour0,nobold,nounderscore,noitalics]#[fg=colour15,bg=colour0] W#I #[fg=colour0,bg=colour15,nobold,nounderscore,noitalics]#[fg=colour0,bg=colour15] P#P #[fg=colour15,bg=colour0,nobold,nounderscore,noitalics]"

# Set the right part of the status bar
set -g status-right-length 900 # Set the length of the right part of the status bar
set -g status-right "#[fg=colour15,bg=colour0] #(cat /etc/*-release | grep -P '^ID=' | cut -c 4-) #[fg=colour0,bg=colour15] #(curl -s ipinfo.io | grep -Po '[0-9]{3}(\.[0-9]{3}){3}') #[fg=colour15,bg=colour0] %R | %d %b #[fg=colour0,bg=colour15] #(whoami)"

# Set the window list
set -g status-justify centre # Center the window list in the status bar

set -g window-status-bell-style fg=colour15,bg=colour0,bold
set -g window-status-format "#[fg=colour15,bg=colour0][ #I #W ]"
set -g window-status-current-format "#[fg=colour0,bg=colour15][ #I #W ]"
set -g window-status-activity-style fg=colour15,bg=colour237,underscore
set -g window-status-current-style fg=colour15,bg=colour0

#################### Pane theme ####################
# Set the pane border style
set -g pane-border-style fg=colour8,bg=colour235
set -g pane-active-border-style fg=colour15,bg=colour244
set -g pane-border-indicators both
set -g pane-border-status top
set -g pane-border-format "[#P$#{pane_pid}]@#{pane_current_path}|<#{pane_tty}>"


#################### Message theme ####################
# Set the message style
set -g message-style fg=colour15,bg=colour1


#################### Command theme ####################
# Set the command style
set -g message-command-style fg=colour5,bg=colour1,bold,italics,underscore



# Set the clock style
set -g clock-mode-colour colour15

# Set the mode style
setw -g mode-style fg=colour0,bg=colour226


