# This is the window configuration file for the tmux

################## Basic Settings ##################
set -g renumber-windows on # renumber windows when a window is closed
set -g base-index 1 # start window numbering at 1
bind-key c new-window -c "#{pane_current_path}" # create a new window in the current directory




################## Status Bar ##################
# 颜色定义
color_main="colour0"
color_accent="colour15"
color_warning="colour1"

# 状态栏基础设置
set -g status-style "bg=#{?client_prefix,colour239,default}"
set -g status-justify centre
set -g status-left-length 60
set -g status-right-length 900

get_os_info="#(zsh -c 'source $DOTFILES/zsh/utilities.sh; get_os_name')"
get_network_info="#(zsh -c 'source $DOTFILES/zsh/utilities.sh; get_public_ip')"

# 时间格式定制
time_format="%H:%M"
date_format="%a %d %b"  # 显示星期+日期

# 状态栏左侧
set -g status-left "\
#[fg=$color_accent,bg=$color_main] ${get_os_info}\
#[fg=$color_main,bg=$color_accent] S#S \
#[fg=$color_accent,bg=$color_main] W#I \
#[fg=$color_main,bg=$color_accent] P#P \
#[fg=$color_accent,bg=$color_main]"


# 状态栏右侧
set -g status-right "\
#[fg=$color_accent,bg=$color_main] \
#[fg=$color_main,bg=$color_accent] ${get_network_info} \
#[fg=$color_accent,bg=$color_main] ${time_format} | ${date_format} \
#[fg=$color_main,bg=$color_accent,bold,italics] #(whoami) "

# 窗口状态样式
set -g window-status-bell-style "fg=$color_accent,bg=$color_main,bold"
set -g window-status-format "[ ###I #W ]"
set -g window-status-current-format "#[fg=$color_accent,bg=$color_main,reverse][ ###I #W ]"
set -g window-status-activity-style "fg=$color_accent,bg=colour239"
set -g window-status-current-style "fg=$color_accent,bg=$color_main"
